### ISSUE TITLE
Compilation failure (lfetool)

### ISSUE THREAD

**Issue by nazarsh** [lfex/yaws-rest-starter#4] opened 2016-05-02 00:25 UTC
with no lfetool installed (since I don't believe instructions called for it)

```
Nazars-MBP-2:yaws-rest-starter nazar$ make compile
make: ./bin/lfetool: Command not found
Getting dependencies ...
/bin/sh: ./bin/lfetool: No such file or directory
make: *** [get-deps] Error 127
```

**Comment by oubiwann** [comment] 2016-05-02 02:26
This is a duplicate of issue #2. It should now be fixed, though! See that ticket for details.

**Closed by oubiwann** 2016-05-02 02:26 UTC
Labels: duplicate
